#!/usr/bin/python
#
# Copyright 2012 Saggi Mizrahi
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
#
# Refer to the README and COPYING files for full details of the license
#

import SocketServer
import threading
import subprocess
import sys
import os
import base64
import shutil
import pwd

from Queue import Queue

PORT_RANGE = xrange(49152, 65535)


class SGvimHandler(SocketServer.BaseRequestHandler):
    def handle(self):
        remote_host = self.client_address[0]
        path = self.request.recv(1024).strip()
        sock_path = get_ssh_sock_path()
        gvim_cmd = ':let g:netrw_sftp_cmd = "sftp -o ControlPath=%s"' % \
            (sock_path,)
        remote_path = "sftp://%s/%s" % (remote_host, path)

        subprocess.Popen(["gvim", "--cmd", gvim_cmd, remote_path])


def start_listener(resp_chan):
    for port in PORT_RANGE:
        try:
            server = SocketServer.TCPServer(("localhost", port), SGvimHandler)
            break
        except:
            pass

    resp_chan.put_nowait(port)
    del resp_chan
    server.serve_forever()


def get_system_dir():
    system_dir = "/tmp/sgvim_%d" % (os.getpid(),)
    try:
        os.makedirs(system_dir)
    except (OSError, IOError):
        pass
    return system_dir


def get_ssh_sock_path():
    system_dir = get_system_dir()
    return os.path.join(system_dir, "ssh.sock")

def run_ssh(host, local_port, remote_port):
    sock_path = get_ssh_sock_path()
    subprocess.call(["ssh", host, "-M", "-S", sock_path, "-t", "-R",
                     "%d:localhost:%d" % (local_port, remote_port),
                     "env BASH_FUNC_gvim\(\)='() { echo $(readlink -f \"$1\") > /dev/tcp/127.0.0.1/%d; }' bash" % (remote_port,)])

def main():
    port_chan = Queue()
    t = threading.Thread(target=start_listener, args=(port_chan,))
    t.setDaemon(True)
    t.start()
    port = port_chan.get()
    del port_chan

    remote_host = sys.argv[1]
    # TODO: Make sure port is free on target aswell
    run_ssh(remote_host, port, port)
    shutil.rmtree(get_system_dir())

if __name__ == "__main__":
    main()
